import { FiSearch } from "react-icons/fi";
import {
  MdShoppingCart,
  MdCategory,
  MdCancel,
  MdArrowBackIosNew,
  MdArrowForwardIos,
} from "react-icons/md";
import {
  AiOutlineEye,
  AiOutlineEyeInvisible,
  AiFillPlusCircle,
  AiFillEdit,
  AiOutlineMenu,
  AiOutlinePlusCircle,
  AiFillSetting,
} from "react-icons/ai";
import {
  FaUserCircle,
  FaAddressCard,
  FaStoreAlt,
  FaTruck,
  FaUserFriends,
  FaArrowAltCircleLeft,
  FaPaintBrush,
  FaFacebookMessenger,
  FaStar,
  FaUserCheck,
  FaShippingFast,
  FaCcPaypal,
} from "react-icons/fa";
import { ImKey, ImAndroid } from "react-icons/im";
import { RiBankCardFill, RiImageAddFill } from "react-icons/ri";
import { GoListOrdered } from "react-icons/go";
import { RxDotFilled } from "react-icons/rx";
import {
  BsFillBookmarkHeartFill,
  BsCameraFill,
  BsTable,
  BsImageAlt,
  BsChevronLeft,
  BsChevronRight,
  BsFillBagCheckFill,
  BsCardList,
  BsFillPhoneVibrateFill,
  BsFillPersonPlusFill,
  BsMessenger,
  BsFacebook,
} from "react-icons/bs";
import {
  IoArrowUndoCircleOutline,
  IoArrowRedoCircleOutline,
  IoStatsChart,
  IoLocationSharp,
  IoCloseSharp,
  IoCheckmarkSharp,
  IoTrendingUpOutline,
  IoTrendingDownOutline,
} from "react-icons/io5";
import { GrProductHunt } from "react-icons/gr";
import { DiMongodb } from "react-icons/di";
import { GrNode, GrReactjs } from "react-icons/gr";
import { SiExpress, SiTailwindcss } from "react-icons/si";
import { FcGoogle } from "react-icons/fc";

export const icons = {
  FaCcPaypal,
  BsFacebook,
  FcGoogle,
  IoTrendingUpOutline,
  IoTrendingDownOutline,
  FaStar,
  AiFillSetting,
  FiSearch,
  MdShoppingCart,
  AiOutlineEye,
  AiOutlineEyeInvisible,
  FaUserCircle,
  FaUserFriends,
  ImKey,
  FaAddressCard,
  FaPaintBrush,
  FaFacebookMessenger,
  RiBankCardFill,
  AiOutlinePlusCircle,
  GoListOrdered,
  BsFillBookmarkHeartFill,
  FaStoreAlt,
  AiFillPlusCircle,
  IoArrowUndoCircleOutline,
  IoArrowRedoCircleOutline,
  BsCameraFill,
  IoStatsChart,
  AiFillEdit,
  BsTable,
  FaTruck,
  MdCategory,
  RiImageAddFill,
  BsImageAlt,
  BsChevronLeft,
  BsChevronRight,
  BsCardList,
  GrProductHunt,
  FaArrowAltCircleLeft,
  BsFillBagCheckFill,
  GoListOrdered,
  RxDotFilled,
  AiOutlineMenu,
  MdCancel,
  MdArrowBackIosNew,
  MdArrowForwardIos,
  SiTailwindcss,
  SiExpress,
  DiMongodb,
  GrReactjs,
  GrNode,
  IoLocationSharp,
  ImAndroid,
  FaUserCheck,
  BsFillPhoneVibrateFill,
  BsFillPersonPlusFill,
  BsMessenger,
  FaShippingFast,
  IoCloseSharp,
  IoCheckmarkSharp,
};
